### ISSUE TITLE
cap_sasl.pl does not identify on reconnect on freenode

### ISSUE THREAD

**Issue by jimerickson** [kaniini/ecdsatool#6]
i am using the cap_sasl.pl script provided by ecdsatool with irssi to connect to freenode. it identifies properly on the initial connect but fails to identify on reconnects. am i doing something wrong or is this a known issue? thanks for all your hard work on ecdsatool.

**Comment by lehitoskin** [comment]
I am having the same issue. Specifically, it fails to load keys on connect after the first successful authentication.

**Comment by kaniini** [comment]
It would be better to use the version on `scripts.irssi.org`, which provides ECDSA support.
